version: '3.9'
services:
  # nginx-proxy:
  #   image:  nginx:stable-alpine
  #   container_name:  nginx-proxy
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - "./nginx.conf:/etc/nginx/nginx.conf:ro" #ro กำหนดเพื่อไม่ให้ไปแก้ไฟล์ 
  #   networks:
  #     # - webproxy
  #     - api
  #   environment:
  #     - VIRTUAL_HOST= www.test.hotelflipper.api
  app1:
    hostname: hotelflipper
    domainname: hotelflipper.api
    build:
      context: . # หาdockerfile ปัจจุบัน
      dockerfile: Dockerfile
    networks:
      - api
      # - microservice_network
      # - webproxy
      # - domain1
    ports: 
      - "8081:3000"
  # app2:
  #   domainname: hotelflipper.api
  #   container_name: Hotel_Flipper_service
  #   image: kudave/hotel-nestjs-service 
  #   ports: 
  #     - "8082:3000"
  #   networks:
  #     - microservice_network
  # rabbitmq:
  #   image: "rabbitmq:management"
  #   container_name: rabbitmq
  #   restart: always

networks:
  api:
    driver: bridge
  # webproxy:
  #   name: webproxy
  #   external: true
  # microservice_network:
  #   external: true
  
  # domain1:
  #   external: true
    