version: '3.7'
services:
  backend:
    container_name: Hotel_Flipper_Payment_order_review_qa
    build:
      context: . # หาdockerfile ปัจจุบัน
      dockerfile: Dockerfile
    port: 
      - "27027:31"